version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:269721309720:task-definition/auditauth:2"
        PlatformVersion: "LATEST"
