version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:269721309720:task-definition/auditseverity:1"
        LoadBalancerInfo:
          ContainerName: "auditseverity"
          ContainerPort: "8080"
        PlatformVersion: "LATEST"